version: '3.8'

services:

  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./oefening1:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./oefening1:/var/www/php
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: syntrafs
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
      UPLOAD_LIMIT: 64M
    depends_on:
      - db