version: '3.1'

services:
  nginx:
    image: nginx:1.21
    ports:
    - 80:80
    volumes:
      - ./php/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.db
    depends_on:
      -php
  php:
    build: ./.docker/php
    working_dir: var/www/php
    volumes: 
      - ./php:/var/www/php
    depends_on:
      - php

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: syntrafs
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db